auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: github
url: http://androidcoder90.github.io
feed: /atom.xml
author_info: <a href="http://www.baidu.com/">androidcoder90</a>
