auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: github
url: http://hilojack.github.io
feed: /atom.xml
author_info: <a href="http://hilojack.sinaapp.com/">hilojack</a>
